### ISSUE TITLE
STANDALONE MODULE : local variable 'note_list' referenced before assignment

### ISSUE THREAD

**Issue by VDB-Robin** [RichardYang40148/mgeval#5]
Hello,

First of all, thank you for your work.
I contact you, because when I try to run the command :

python . <path/to/first/sample/directory> <path/to/second/sample/directory> <output_filename>

I get an error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/content/mgeval/__main__.py", line 96, in <module>
    tmp = evaluator(feature, 0, args.num_bar)
  File "./mgeval/core.py", line 101, in bar_used_pitch
    used_pitch[i] = len(set(note_list[current_note:current_note + int(used_notes[i][0])]))
UnboundLocalError: local variable 'note_list' referenced before assignment
```

How can I solve this problem?

Thanks in advance,

Robin

**Comment by DreVla** [comment]
I am having the same problem... not sure how to fix it
